module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.4

require github.com/gosexy/gettext v0.0.0-20160830220431-74466a0a0c4a // go-xgettext

require github.com/jessevdk/go-flags v1.6.1 // indirect
