name: OpenCloud Global Build (LS220D)
on: [push] # あなたが git push したら工場が稼働します

jobs:
  armv7-build:
    runs-on: ubuntu-latest # 最新のLinuxサーバーをレンタル
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4 # ソースコード一式を工場に搬入

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Go職人を呼び出す
  
      - name: Install ARM Cross-Compiler
        run: |
          # 1. 工場に「ARM（armhf）も扱うぞ」と宣言する
          sudo dpkg --add-architecture armhf
          
          # 2. 棚卸し（アップデート）をしてARM用の在庫を確認する
          sudo apt-get update
          
          # 3. コンパイラと、今度こそARM用のlibcryptをインストール
          sudo apt-get install -y gcc-arm-linux-gnueabihf libcrypt-dev:armhf

      - name: Build All Services
        run: |
          cd opencloud
          go mod vendor

          # CCも「hf」付きを指名！
          CGO_ENABLED=1 \
          GOOS=linux \
          GOARCH=arm \
          GOARM=7 \
          CC=arm-linux-gnueabihf-gcc \
          go build -v -tags 'netgo' -ldflags '-s -w' -o bin/opencloud ./cmd/opencloud



      - name: Archive Production
        uses: actions/upload-artifact@v4
        with:
          name: opencloud-ls220d-binary # 出来上がった製品の名前
          path: opencloud/bin/ # 焼き上がったバイナリが入っている場所
