name: Build-OpenCloud-LS220D
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Stage 1 Generate
        run: make generate
      - name: Stage 2 Prepare Sysroot
        run: |
          mkdir -p $GITHUB_WORKSPACE/sysroot
          curl -L https://github.com/debuerreotype/docker-debian-artifacts/raw/dist-armhf/bookworm/rootfs.tar.xz -o rootfs.tar.xz
          tar -C $GITHUB_WORKSPACE/sysroot -xJf rootfs.tar.xz ./lib/arm-linux-gnueabihf ./usr/lib/arm-linux-gnueabihf ./usr/include ./usr/lib/gcc/arm-linux-gnueabihf
      - name: Stage 3 Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf
      - name: Stage 4 Build
        run: |
          export GOOS=linux
          export GOARCH=arm
          export GOARM=7
          export CGO_ENABLED=1
          SYSROOT=$GITHUB_WORKSPACE/sysroot
          export CGO_CFLAGS="--sysroot=$SYSROOT"
          export CGO_LDFLAGS="--sysroot=$SYSROOT"
          export CC=arm-linux-gnueabihf-gcc
          make -C build